### ISSUE TITLE
vrp_garage Sell Function

### ISSUE THREAD

**Issue by blinkfl** [Sighmir/FiveM-Scripts#2]
I noticed that in the script you added the lang string for menu9 "Sell" but I didn't got the sell function to work, or even found in the script. It is a bug or you didn't create the sell function ?? and If you didn't created the sell function, could you explain to me what I need to do to create this function in your vrp_garage script?

**Comment by Sighmir** [comment]
I am sorry but I don't really have time to help with modifications to the code, good luck!
